ingress:
  cert_arn: arn:aws:acm:us-east-1:753119227612:certificate/4f4780e6-4c03-4355-aaba-b1030bfdeb4e
  host: panel-recruitment-quality.sre.nielsen.com

image:
  registry: registry.gitlab.com/nielsen-media/panel-management/one-media-recruitment/panel-recruitment-quality
  tag: 1.2.4

replicas: 2

healthcheck:
  path: /usremoterecqa/service/health

container:
  port: 8070

rds:
  appToken:
  appGateway:
  host:
  username:
  password:
  googleClientID:  
  googleClientSecret:
  googleRedirectUri:
  gmailAccessToken:
  gmailRefreshToken: