ingress:
  cert_arn: arn:aws:acm:us-east-1:565189415401:certificate/6ed78230-244f-4eda-a249-a80287395fa5
  host: panel-recruitment-quality.sre.nielsen.com

image:
  registry: registry.gitlab.com/nielsen-media/panel-management/one-media-recruitment/panel-recruitment-quality
  tag: 2.6.8.1

replicas: 2

healthcheck:
  path: /usremoterecqa/service/health

container:
  port: 8070

env:
  APP_TOKEN:
  APP_GATEWAY_PATH:
  DB_HOST:
  DB_PASSWORD:
  DB_USERNAME:
  GOOGLE_CLIENT_ID:
  GOOGLE_CLIENT_SECRET:
  GOOGLE_REDIRECT_URI:
  GMAIL_ACCESS_TOKEN:
  GMAIL_REFRESH_TOKEN: